                            ___             
                        __ /\_ \            
 _____   __  __  _____ /\_\\//\ \     ___   
/\ '__`\/\ \/\ \/\ '__`\/\ \ \ \ \   / __`\ 
\ \ \L\ \ \ \_\ \ \ \L\ \ \ \ \_\ \_/\ \L\ \
 \ \ ,__/\/`____ \ \ ,__/\ \_\/\____\ \____/
  \ \ \/  `/___/> \ \ \/  \/_/\/____/\/___/ 
   \ \_\     /\___/\ \_\                    
    \/_/     \/__/  \/_/                    


FAIL
2019OCT26
* problem with input files of differing types to .jpg

* error reported
- without debug
./process.py -i $HOME/work/flickr/2019/2019OCT/2019OCT26/* -o $HOME/work/flickr/2019/2019OCT/2019OCT26/u
.Warning: file not processed
	<2019OCT261432261.png>

- debug
./process.py -i $HOME/work/flickr/2019/2019OCT/2019OCT26/* -o $HOME/work/flickr/2019/2019OCT/2019OCT26/u
> path: </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> tools.get_filenames.filepath </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> tools.get_filenames.fpn </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/*.*>
> tools.get_filenames <['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']>
> files ['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']
> destination: (2) <['/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432261.png', '/Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg']>
> processing
> source </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d> <2019OCT261432260.jpg>
.
> source fp </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d>
> dest   fp </Users/pr/work/flickr/2019/2019OCT/2019OCT26/u>
> src </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d/2019OCT261432260.jpg>
> dest </Users/pr/work/flickr/2019/2019OCT/2019OCT26/u/2019OCT261626480.267.jpg>
> height <384>
> width  <685>
> ratio <1.7838541666666667>
> setting image w<1330> h<745> r<1.7838541666666667>
> 1330:745
> <2019OCT261626480.267.jpg>
	format(JPEG) size((1330, 745)) mode:(RGB)
> source </Users/pr/work/flickr/2019/2019OCT/2019OCT26/d> <2019OCT261432261.png>
Warning: file not processed
	<2019OCT261432261.png>

FAIL
2019SEP21
* problem with sys module in pil_tools.py
- known: we identifing an mp4 file

* error reported:

    OSError: cannot identify image file '/Users/pr/work/flickr/2019/2019SEP/2019SEP21/d/IMG_6353.m4v'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "./process.py", line 130, in <module>
        main()
      File "./process.py", line 114, in main
        process(s_fp, dest_fp, s_fn, d_fn)
      File "./process.py", line 51, in process
        pil_resize(src_fp, dest_fp, s_fn, d_fn)
      File "/Users/pr/work/code/py/pypilo/pil_tools.py", line 142, in pil_resize
      sys.exit(1)
      NameError: name 'sys' is not defined

* what I found: 
- trying to process a list of files, the code ran into a mp4 file and threw an error

* steps to reproduce:

   ./process.py -i $HOME/work/code/flickr/2019/2019SEP/2019SEP21/d -o $HOME/work/code/flickr/2019/2019SEP/2019SEP21/u

* what I want:
- to be able to process files with various different file types and handle the result.
 
2019SEP14
1 * problems with resizing
  - specified image constraints (by H)
  - resized the image by percentage (h/3.5 and w/3.5
  - but this wrong so work this out so the ratio is maintained

1 * problems with selecting filenames in uppercase
  - can't re ad filenames if uppercase
